### PR TITLE
resolves #1091 apply page layout specified on page break even when break falls at page boundary

### LINKED ISSUE #1091: Page layout (landscape/portrait) stuck in landscape.
When using Asciidoctor PDF backend, 
```
[.landscape]
<<<
``` 
works to flip the page, but 
```
[.portrait]
<<<
``` 
doesn't flip it back.

The `[.landscape]` and `[.portrait]` directives are in a nested document; observed behavior is (obviously) in the document that includes it.

This is my setup (Windows 10):
```bash
$ ruby -v
ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]

$ asciidoctor -v
Asciidoctor 2.0.9 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]) (lc:IBM437 fs:Windows-1252 in:IBM437 ex:IBM437)

$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.alpha.18 using Asciidoctor 2.0.9 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]) (lc:IBM437 fs:Windows-1252 in:IBM437 ex:IBM437)
```

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by dalemartin** [comment]
Layout is no longer stuck in landscape, works like a charm. Couple new issues though:
* I'm losing my running header completely
* Footer formatting is not right (I realize that's being handled elsewhere)
* Not sure but it seems like `pdfwidth=100%` doesn't work to get an image to fill the landscape width? Shouldn't it scale up to 100% by default without me specifying that anyway? In either case, it's not filling the width of the page. Maybe it's height constrained by the invisible header...

**Comment by dalemartin** [comment]
Actually I'm pretty sure that last bullet is because of the height of my image. The footer (and presumably the invisible header) margins are much larger than on the portrait pages.

As a side note, is there any way of using `[%rotate]` for tables/images instead of changing the page layout?

**Comment by mojavelinux** [comment]
> I'm losing my running header completely

This is a known issue in alpha.18 that will be fixed in beta.1. See #1087.

> Footer formatting is not right

I'm assuming you mean the margins are off.

> Actually I'm pretty sure that last bullet is because of the height of my image filling the vertical space.

Yes, that's correct. It still has to fit height-wise.

**Comment by mojavelinux** [comment]
> As a side note, is there any way of using [%rotate] for tables/images instead of changing the page layout?

Prawn table does not support rotation.

**Comment by mojavelinux** [comment]
It sounds like #1027 is crucial to fix to make page layout changes viable. I'll have a closer look at that PR.

**Comment by dalemartin** [comment]
> > Footer formatting is not right
> 
> I'm assuming you mean the margins are off.
The margins are off, yes, but specifically the horizontal line and page number are short, the same width as the portrait pages. A separate issue was opened about it already #1036.

**Comment by mojavelinux** [comment]
Yes, that's what I meant. :+1:

**Pull request merged**
