### PR TITLE
use pygments.rb 2.0.0 in CI

### PR DESCRIPTION
**Pull request by slonopotamus**

### CODE REVIEW

**Comment by slonopotamus** [comment]
Huh. `expect().not_to raise_exception` has caught exception from _another_ `expect()` inside it.

**Comment by slonopotamus** [comment]
```
    it 'should not crash when adding indentation guards' do
      (expect do
        pdf = to_pdf <<~'EOS', analyze: true
        :source-highlighter: pygments

        [source,yaml]
        ----
        category:
          hash:
            key: "value"
        ----
        EOS
        (expect pdf.find_text 'category:').to have_size 1
        (expect pdf.find_text %(\u00a0 hash:)).to have_size 1
        (expect pdf.find_text %(\u00a0   key: )).to have_size 1
        (expect pdf.find_text '"value"').to have_size 1
      end).not_to raise_exception
    end
```

With new pygments, semicolon is no longer bold, so `category:` string is split into `category` (bold) + `:` (regular).
@mojavelinux do you have any idea if this is OK and test needs to be adjusted or something broke?

**Comment by mojavelinux** [comment]
Syntax highlighting for YAML is always changing ;) It's fine to update the test. We don't actually care that much how the syntax highlighting is done. We are just verifying that it is done. So the specifics don't really matter here.

**Comment by slonopotamus** [comment]
I'm not sure how to adjust `find_text` assertion, could you help please?

**Comment by mojavelinux** [comment]
find_text looks for chunks. So update the find_text calls to look for the strings that are isolated, as you described in your first comment. So `(expect pdf.find_text 'category').to have_size 1` for example.

**Comment by slonopotamus** [comment]
So, do you want anything else here? I believe this PR is ready for merge.

**Comment by mojavelinux** [comment]
I've just been really busy the past few weeks, so I haven't had a chance to do much with Asciidoctor PDF. I'll be getting back to it soon as I wan to get serious about wrapping up the 2.0 release.

**Comment by mojavelinux** [comment]
Thanks!

**Pull request merged**
