### PR TITLE
Add table inner border color and width

### PR DESCRIPTION
**Pull request by ntfc**
Add two new properties to control a table inner borders styling: `table_border_inner_color` and `table_border_inner_width`.

### CODE REVIEW

**Comment by ntfc** [comment]
Hi,

Any change of this getting merged?

**Comment by mojavelinux** [comment]
Hey @ntfc! Sorry for the delay. I'll review this asap.

**Comment by mojavelinux** [comment]
To be consistent with the terminology in AsciiDoc, I'd like to refer to these borders as "the grid".

```yaml
table_grid_width: 0.5
table_grid_color: '000000'
```

If these keys are not set, I'd like to fallback to the border color.

I'll send a PR to your branch proposing these changes.

**Comment by mojavelinux** [comment]
PR sent. Let me know if that change looks acceptable to you.

**Comment by mojavelinux** [comment]
By the way, thanks again for supporting Asciidoctor! I've added you to the [supporters page](http://asciidoctor.org/supporters/).

**Comment by ntfc** [comment]
Hi Dan,

No worries, I kind of forgot about this too. Your changes look good, I'll accept them later today.

Thanks!

**Comment by ntfc** [comment]
I have added your changes to the PR

**Comment by mojavelinux** [comment]
Thanks @ntfc! Your work has been merged as 5c6ea8751b583177e07d004538e88c8a07ae2049. I also added the new keys to the theming guide.

**Pull request closed without merging**
