### PR TITLE
enable font_fallbacks support

### PR DESCRIPTION
**Pull request by chloerei**
Let editor can use font fallbacks settings in themes.

### CODE REVIEW

**Comment by chloerei** [comment]
Relate to https://github.com/asciidoctor/asciidoctor-pdf/issues/58

**Comment by mojavelinux** [comment]
The fallback_fonts feature was previously disabled because it was breaking global styling. This was fixed in Prawn 1.2.1 as described in the following section in the release notes:

https://github.com/prawnpdf/prawn/wiki/CHANGELOG#fallback-fonts-no-longer-break-global-font-styling

It's safe to use this feature. I just confirmed it works as expected.

**Comment by mojavelinux** [comment]
Thanks for fixing this, @chloerei!

**Comment by mojavelinux** [comment]
I'm going to reenable the fallback_fonts in the default asciidoctor theme to use the already provided M+ 1p multilingual font. We know it doesn't cover all CJK characters, but at least it catches some for now. We'll address more complete support as part of #82.

**Pull request merged**
