### PR TITLE
resolves #1204 use consistent line height for list items and toc entries if text is entirely monospace

### LINKED ISSUE #1204: Unordered list bullet + literal = wrong vertical bullet alignment
tested in beta2 and current master

```
= test

== test 1
* hello
** world
** `world`
** world `world`
** w``orld``
* hello
* `hello`
* hello
```

With everything default outputs pdf:

image

Note if list item starts with inline literal the bullet is misaligned. 

PS, boxes and arrows are added afterwards to illustrate the issue.

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
@habamax want to give this a try?

**Comment by habamax** [comment]
Looks good for me. Tested with 3 docs that had this issue (removing handwritten `{zwsp}`s)

**Comment by habamax** [comment]
Although the name of the fix "...if text is entirely monospace" is not true for me -- it also works if text is not entirely monospaced:

```
* `I` -- Inserted
* `U` -- Updated
```

**Comment by mojavelinux** [comment]
Thanks for confirming!

> it also works if text is not entirely monospaced:

I'm not able to reproduce this. But I guess it doesn't really matter since the fix would solve it anyway.

**Pull request merged**
