### PR TITLE
resolves #1500 remove prawn-table from bundle so Travis doesn't reupload

### LINKED ISSUE #1500: Travis CI cache is reuploaded for every build
For example: https://travis-ci.org/asciidoctor/asciidoctor-pdf/jobs/637866445#L655

```
store build cache
$ bundle clean
changes detected (content changed, file is created, or file is deleted):
/home/travis/build/asciidoctor/asciidoctor-pdf/.bundle/gems/ruby/2.5.0/bundler/gems/prawn-table-515f2db29486/.git/index
/home/travis/build/asciidoctor/asciidoctor-pdf/.bundle/gems/ruby/2.5.0/bundler/gems/prawn-table-515f2db29486/.git/logs/HEAD
changes detected, packing new archive
uploading master/cache--linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--rvm-2.5.7--gemfile-Gemfile.tgz
cache uploaded
```

I believe this happens for every build.

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by slonopotamus** [comment]
You need to run `bundle clean` manuall before removing. Travis tries to run `bundle clean`, but it happens after you remove prawn-table, so `bundle clean` fails: https://travis-ci.org/asciidoctor/asciidoctor-pdf/jobs/640325055#L683

**Comment by slonopotamus** [comment]
I dunno, maybe there's some command to _uninstall_ a gem?

**Comment by mojavelinux** [comment]
I figured out that all we need to do it remove the .git directory. All other permutations lead to some sort of error.

**Comment by mojavelinux** [comment]
> I dunno, maybe there's some command to uninstall a gem

There is, but then it complains it's not installed since it's listed in the gemspec.

**Comment by mojavelinux** [comment]
I need to merge this to see if it really works. I might have to make follow-up commits to refine.

**Pull request merged**
