### PR TITLE
upgrade CI dist to bionic

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by slonopotamus** [comment]
> use 2.6.5 as the default Ruby since it's pre-installed

[2.7 also installs in no time](https://travis-ci.org/asciidoctor/asciidoctor-pdf/jobs/640846074#L280), possibly [docs](https://docs.travis-ci.com/user/reference/bionic/#ruby-support) are outdated a bit.

**Comment by mojavelinux** [comment]
Yeah!

**Comment by mojavelinux** [comment]
However, it seems like JRuby doesn't like bionic.

**Comment by mojavelinux** [comment]
I decided to take your advice and drop the Lint stage. I was able to name the first job in the Test stage, which is good enough for me.

**Comment by mojavelinux** [comment]
We have to run JRuby tests on trusty still.

**Comment by mojavelinux** [comment]
Lookin' good at 12min.

**Pull request merged**
