### PR TITLE
Drop workaround for Bundler 2.2.0 on JRuby on Windows bug

### PR DESCRIPTION
**Pull request by slonopotamus**
It was fixed in Bundler 2.2.1

### CODE REVIEW

**Comment by slonopotamus** [comment]
Err... Wut.

**Comment by slonopotamus** [comment]
I believe that build failure is not caused by my changes.

**Comment by mojavelinux** [comment]
It's possible it's due to a change in Bundler. It seems to be having difficulty resolving the prawn-table gem from git. Perhaps kick the build again?

**Comment by slonopotamus** [comment]
Hmm... Good point. Seems like I cannot convert PR into a WIP after I created it normally. Pretend that it is WIP starting from NOW :D

**Comment by slonopotamus** [comment]
Okay, seems like Bundler 2.2.x is still a bit broken on JRuby + Windows. Need to bugreport it to Bundler.

**Comment by slonopotamus** [comment]
Reported: rubygems/rubygems#4195

**Comment by mojavelinux** [comment]
Thank you for your diligence in following up on this. :trophy:

**Pull request closed without merging**
