### PR TITLE
Upgrade prawn-svg

### PR DESCRIPTION
**Pull request by henry-hsieh**
Hello,

I'm using [bytefield-svg](https://github.com/Deep-Symmetry/bytefield-svg) which is heavily using the `dominant-baseline` of SVG attribute to make the texts center-aligned. However, [prawn-svg](https://github.com/mogest/prawn-svg) cannot recognize the attribute. Therefore, I made a [PR](https://github.com/mogest/prawn-svg/pull/158) to support the feature, and it has been merged into main branch successfully. Moreover, the newest release [0.33.0](https://github.com/mogest/prawn-svg/releases/tag/v0.33.0) has included the feature. I hope the asciidoctor-pdf can upgrade it as well.

Thank you!

### CODE REVIEW

**Comment by mojavelinux** [comment]
Three of the visual tests are failing. However, when I inspect the changes manually, I cannot perceive any difference, so likely it is some sort of rounding difference. Therefore, I'll update the expected output files and proceed.

**Comment by henry-hsieh** [comment]
OK. Thanks for your help!

**Comment by henry-hsieh** [comment]
Hi @mojavelinux , is it possible to upgrade the version of the release recently? I want to update the dependency of my project. Thank you!

**Comment by mojavelinux** [comment]
I don't have any plans for an immediate release, but once I come back around to the project and make a few other updates, I'll push out a release.

**Comment by henry-hsieh** [comment]
OK. I'll wait for the release. Thanks!

**Pull request merged**
