### PR TITLE
accurately trap LoadError from CodeRay if source language is not recognized on code block

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
cc: @abelsromero

**Comment by abelsromero** [comment]
Thanks!

**Comment by abelsromero** [comment]
Not that I did not trust the fix :smile: ... I run the maven examples against this version and is working fine :+1:

**Comment by mojavelinux** [comment]
Thanks @abelsromero! I always love more testing.

**Pull request merged**
