### PR TITLE
resolves #631 let theme control which toc levels have dot leaders

### LINKED ISSUE #631: Allow dot leaders in toc to be hidden per section level
Allow the dot leaders between the section title and the page number to be hidden per section level, as they are not always desired.

We're considering several proposals for configuring this setting in the theme:

```yaml
toc:
  h2_dot_leader_visibility: hidden
```

or

```yaml
toc:
  dot_leader_levels: 2 3 4
```

or

```yaml
toc:
  dot_leader_visibility: hidden, hidden, visible, visible, visible
```

If not specified, the dot leaders are shown for all levels.

### PR DESCRIPTION
**Pull request by mojavelinux**
- add toc_dot_leader_levels key to theme (0-based)
- default to using dot leaders for all levels
- slightly optimize how dot leaders are managed

### CODE REVIEW

**Comment by habamax** [comment]
How do I apply this PR to a forked asciidoctor-pdf?

**Comment by mojavelinux** [comment]
Did you figure it out?

**Comment by habamax** [comment]
yep, git remote add mojavelinux yourpersonalrepo etc

**Comment by mojavelinux** [comment]
:+1:  The README needs to be clearer about how to do this.

**Pull request merged**
