### PR TITLE
Add support for quoted text attributes (prefixed in square brackets)

### PR DESCRIPTION
**Pull request by Hextremist**
Supports all the types listed in the examples for asciidoc:
http://www.methods.co.nz/asciidoc/chunked/ch10.html
I.e. work for underline, overline, line-through, colors, big and
small.

### CODE REVIEW

**Comment by Hextremist** [comment]
Hi, I did some changes to make underline, colors etc work as for the Asciidoctor HTML format.

**Comment by Hextremist** [comment]
Sorry new user when it comes to pull requests on GitHub.  Trying again :-)

**Comment by igagis** [comment]
Absence of line-through and underline and red and blue colours blocks the use of potential asciidoc-diff utility

**Comment by git-ere** [comment]
I came over the same problem:
[stackoverflow discussion](http://stackoverflow.com/questions/33646995/asciidoc-pdf-how-to-use-custom-styles)

I've tried to fix this issue and I think I've got a solution. As I never did Ruby programming neither know the ascidoctor architecture, below I describe the code changes I did.

Pls feel free to comment.
changed line 1817 of [converter.rb](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/converter.rb)
old:
 ` quoted_text = %(<span class="#{role}">#{open}#{node.text}#{close}</span>)`

new:
  ```
style = add_style style, role, 'font-style', 'font_style'
  style = add_style style, role, 'font-size', 'font_size'
  style = add_style style, role, 'color', 'font_color'
  quoted_text = %(<span style="#{style}">#{open}#{node.text}#{close}</span>)
```

added method in [converter.rb](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/converter.rb)

  ```
def add_style (style, role, styleName, *themeName)
    themeName = themeName ? themeName.first : styleName
    value = eval %(@theme.#{role}_#{themeName})
    if value
       if style
         style = %(#{style};)
       end
       style = %(#{style}#{styleName}:#{value})
    end
    return style
  end
```

added lines in [transform.rb](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/formatted_text/transform.rb)

added after line 225

```
  when 'font-size'
    unless fragment[:size]
      fragment[:size] = pvalue
    end
```

I've just tested with some styling properties. If ok all of [theming-guide](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc) should propably being added.

**Comment by mojavelinux** [comment]
I'm cherry picking from this pull request to make the changes easier to track. I've implemented the underline and line-through roles thus far.

I'm planning to map big and small to the base_font_size_large and base_font_size_small theme settings.

I'm still thinking about the best way to handle the colors.

**Comment by Patola** [comment]
Any progress on the color dealing in asciidoctor?

**Comment by jlozadad** [comment]
any update on this?

**Comment by mojavelinux** [comment]
This has now been implemented, mainly as part of #368.

The only thing not implemented is the background and border for custom roles. However, it wouldn't be too much effort to add it to the current implementation. If that's needed, let's pursue it as a separate issue.

**Pull request closed without merging**
