### PR TITLE
Add Dependabot config

### PR DESCRIPTION
**Pull request by slonopotamus**
Dependabot is a tool that automatically checks for updates of dependencies and creates pull requests

### CODE REVIEW

**Comment by mojavelinux** [comment]
I don't like dependabot. The notifications annoy me. I prefer to upgrade dependencies when I choose to update dependencies.

**Comment by mojavelinux** [comment]
The problem is two fold:

1. I cannot stand automated PRs. They are noise.
2. Dependabot lack context. I don't want to just blindly update dependencies. Security vulnerabilities are an exception. Those are warranted.

I'd be okay with security vulnerability notifications. But then, GitHub already provides that.

**Comment by slonopotamus** [comment]
> I don't want to just blindly update dependencies.

I think this needs clarification. Dependabot is not about "let's always use the latest version". It is about "adjust dependency spec the way that it _doesn't prevent user from using latest dependency version_.

**Comment by mojavelinux** [comment]
And what dependabot wants may not align with our dependency policy. I'm not going to let a bot be in control of this repository. I have a fundamental disagreement with the vision of the dependabot project about what purpose it should serve.

**Comment by slonopotamus** [comment]
Okay, no problem

**Comment by mojavelinux** [comment]
I apologize if I came across a bit edgy. I'm just witnessing dependabot spam the hell out of repositories I watch and I think it's wasting time and damaging OSS productivity. It's turning the focus to endless churn of pointless dependency updates instead of on improving the software. And it really upsets me.

I want to clarify that security vulnerabilities are a completely different matter and I do respect the importance of addressing those urgently.

**Pull request closed without merging**
