### PR TITLE
resolves #620 Add support for pdfwidth to inline images

### LINKED ISSUE #620: Add support for pdfwidth to inline images
pdfwidth does not work for an inline image.

```
image:model_spy_targetplatform.png[pdfwidth=1%]
```

image

I upload soon an example via a PR.

### PR DESCRIPTION
**Pull request by fap-**

### CODE REVIEW

**Comment by mojavelinux** [comment]
This is great, except I don't think we should support vw units or the theme fallback. vw units don't make sense in this context (and require special handling anyway). The theme fallback is intended for block images only. Inline images should be sized explicitly.

Here's how I propose to write the line.

```ruby
width_attr = (width = resolve_explicit_width node.attributes, bounds.width) ? %( width="#{width}") : nil
```

**Comment by mojavelinux** [comment]
I've rewritten the PR and pushed it to the PR branch. Take a look and see what you think.

Here's a summary of what I changed:

* I create a `preresolve_explicit_width` image to more clearly describe that we are doing a partial resolution of the explicit width by resolving absolute units, but not relative ones
  - I also included support for the `scaledwidth` attribute
* I simplified the resolution of percentage value in the arranger
* I constrained the width of the image to the width of the bounds (in this context, a image larger than the available width doesn't make sense and causes Prawn to loop infinitely)

If you set the pdfwidth to 100%, we still run into the issue described in #388. However, I now understand why that is happening and can fix it. The spacer is wider than the available width and Prawn attempts to render the image again on each wrapped line.

**Comment by fap-** [comment]
Wow, thank you, looks good to me.

My hack to fix #388 would look like this, but there is probably a better solution. (with the prawn api that you are mentioning in the comment?)

```
        if ((number = (fragment[:image_width] / spacer_w).ceil) * spacer_w) < doc.bounds.width
          fragment[:text] = ImagePlaceholderChar * number
        else
          fragment[:text] = ImagePlaceholderChar * (fragment[:image_width] / spacer_w).floor
        end
```

**Comment by mojavelinux** [comment]
Indeed! That's almost identical to what I was going to propose, so we're on the same wavelength.

```ruby
if (spacer_cnt = (fragment[:image_width] / spacer_w).ceil) * spacer_w > available_w
  spacer_cnt -= 1
end
fragment[:text] = ImagePlaceholderChar * spacer_cnt
```

We know if it's too much, it will be exactly 1 too many.

There's really no other way I can think of to fix it unless we complete rethink how space is allocated. And for that to happen would probably require a change to Prawn or to patch a significant part of it. We might be able to get some more fine tuning using character spacing, but I'll need to experiment to know if that helps us.

**Pull request merged**
