### PR TITLE
Add example for specifying theme file

### PR DESCRIPTION
**Pull request by leif81**
See issue #61 for my confusion that lead to adding this example here.

### CODE REVIEW

**Comment by bfad** [comment]
This is no longer part of the documentation, and it should be re-added or the documentation should be updated with the correct way to do this.

**Comment by mojavelinux** [comment]
Isn't it here?

https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#applying-your-theme

If there's information missing from that section that you need, please let me know and I'll add it.

**Comment by bfad** [comment]
I missed the "and applying" part when reading the README. That has everything I need, thanks!

**Comment by mojavelinux** [comment]
Great! I'm glad to hear that. Thanks for replying.

**Pull request merged**
