### PR TITLE
resolves #85 place footnotes at end of chapter (book) or document (article)

### LINKED ISSUE #85: Footnotes are not positioned correctly
I trying to use footnotes with pdf like

image

in pdf it doesn't display correctly

image

Thanks

### PR DESCRIPTION
**Pull request by mojavelinux**
- place list of footnotes at end of chapter (when doctype is book) or document (when doctype is article)
- add footnotes category to theme to style footnote list
- add additional footnotes to example documents
- honor footnotes-title attribute to control title of footnote list (unset by default)

### CODE REVIEW

**Comment by bcourtine** [comment]
I tested your PR and it looks good to me.

**Comment by bcourtine** [comment]
I thought of an evolution, but don't know how to implement it: if `footnotes-title` is defined, corresponding page could be added to the TOC (maybe with another option `footnotes-toc`).

**Comment by mojavelinux** [comment]
I don't think that's the right use of a section heading. Footnotes are not a discrete section or appendix. They are an addendum to a section (chapter for book or document for article). Therefore, I conclude that they map closer to a block (as I have done it) than a section.

**Comment by bcourtine** [comment]
Seems legit with your enhancements. I was still thinking about my first version where all footnotes were in a unique end section (sometimes several pages long).

**Comment by mojavelinux** [comment]
Indeed, if you have chapters, the footnotes should be broken up by chapter. They would only appear at the very end if you have no chapters or it's an article. This is consistent with how I've seen footnotes be handled in ebooks.

**Comment by gAmUssA** [comment]
@mojavelinux which version of asciidoctorj we have this feature?

**Comment by mojavelinux** [comment]
The version of AsciidoctorJ PDF matches the version of Asciidoctor PDF.
Just consult the changelog (search for 85) and you will know.

>

**Pull request merged**
