### PR TITLE
resolves #65 support setting page size via attribute

### LINKED ISSUE #65: Be able to set custom page sizes for pdf
Hello

Would it be possible to add the ability to set custom page sizes such as A5 or using any custom dimensions such as 134mm x 233mm etc.

Specifically targeting Printed Books

### PR DESCRIPTION
**Pull request by mojavelinux**
- support setting page size via pdf-page-size attribute
- add support for units in page size
- validate named page size
- document page size options in default theme file

### CODE REVIEW

**Comment by mojavelinux** [comment]
@IbnSaeed how does this look?

**Comment by IbnSaeed** [comment]
Excellent. Thanks alot for adding this feature.

**Comment by mojavelinux** [comment]
Sure thing!

One thing I wasn't sure about is whether to make the layout (i.e., orientation) a document-level attribute too. Technically, switching the layout between portrait and landscape can be accomplished simply by flipping the values in the pdf-page-size. In fact, that's all setting the layout to landscape does (in Prawn, at least).

I was also wondering if we should support an alternate syntax for the value using `x` as a delimiter:

```
:pdf-page-size: 8.25in x 11.69in
```

Do you think that's worth doing or is the array-like syntax sufficient?

**Comment by IbnSaeed** [comment]
I use LaTeX with memoir class for book layouts and this is how its defined in memoir|

`
\setstocksize{9in}{4in}
`
The array syntax would be sufficient `pdf-page-size: [8.25in, 11.69in]`, is fine by me.

If its not a hassle, you could add a LaTeX style syntax as well .

**Comment by mojavelinux** [comment]
I think I'm going to move forward with the syntax I proposed. It just seems very natural and not difficult to parse.

> If its not a hassle, you could add a LaTeX pdf-page-size{9in}{4in} style syntax as well .

I'm not considering that since the goal of AsciiDoc is not to mimic LaTeX, only to provide a suitable replacement. It's important to adhere to the AsciiDoc style for our syntax.

**Comment by mojavelinux** [comment]
The `width x height` syntax is now implemented (will be available in 1.5.0.alpha.8).

**Pull request merged**
