### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by djencks**
keep together is not documented anywhere, but it's easy to use once you discover how.

### CODE REVIEW

**Comment by mojavelinux** [comment]
I agree we need to draw attention to this feature, but this change removes mention of the default keep together behavior for all other blocks. In other words, open blocks are not keep together by default, requiring the unbreakable option to be set. All other delimited blocks keep together by default.

**Comment by mojavelinux** [comment]
This still isn't correct. Only open blocks support the unbreakable option. All other delimited blocks are implicitly unbreakable. I think these should be two separate points.

**Comment by djencks** [comment]
My impression is that paragraph blocks and section blocks are not unbreakable, so your claim about "the default keep together behavior for all other blocks" isn't accurate either.  Is it explicitly delimited blocks + open blocks with [%unbreakable] that are unbreakable?

**Comment by mojavelinux** [comment]
I said all other **delimited** blocks. That excludes sections and paragraphs.

**Comment by mojavelinux** [comment]
>  Is it explicitly delimited blocks + open blocks with [%unbreakable] that are unbreakable?

Correct.

**Comment by djencks** [comment]
I quoted your first comment.

**Comment by djencks** [comment]
Are tables and lists unbreakable?

**Comment by mojavelinux** [comment]
Lists no.

Tables are a bit of a hybrid, and all behavior is controlled by prawn-table. I think cells try to stay together, but there are numerous edge cases I haven't explored.

**Comment by djencks** [comment]
based on how paged.js does, paginating tables properly is very difficult!

**Comment by mojavelinux** [comment]
This is great. Thanks!

**Pull request merged**
