### PR TITLE
fixes #56 Quick fix to restore cross references functionality

### LINKED ISSUE #56: Cross references don't jump to linked section
I tried asciidoctor-pdf today. It's looking really nice on my sample document!
One thing I noticed is that cross references are clickable within the pdf, but the user isn't taken to the target. I'm not 100% sure if cross references should already work or not.

Using asciidoctor-pdf-1.5.0.alpha.5 and a slightly modified example.adoc, see below.

```AsciiDoc
= Document Title
Doc Writer <doc@example.com>
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing

A simple cross reference <<Introduction>>.



== Introduction

A paragraph followed by a simple list with square bullets.

[square]
* item 1
* item 2


Here's how you say "`Hello, World!`" in Prawn:

.Create a basic PDF document using Prawn
[source,ruby]
----
require 'prawn'

Prawn::Document.generate 'example.pdf' do
  text 'Hello, World!'
end
----
```

### PR DESCRIPTION
**Pull request by DavidGamba**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Here's the example you posted wrapped in a code block.

```
[[tuned_table]]
.Tuned Profile for RHEL OSP 6 Environment
|====
^|Tuned Profile ^|System Role
| throughput-performance | Controller node(s)
| throughput-performance | Provisioning node
| virtual-host | Compute node(s)
|====

. Activate the appropriate tuned profile for the corresponding nodes.
Information on what tuned profile to set can be found within the <<tuned_table>> table.
```

**Comment by mojavelinux** [comment]
Superseded by #111.

@rlopez133 your issue will be address by #110.

**Comment by mojavelinux** [comment]
Thanks for sending this pull request, @DavidGamba. It got me started, but I needed to add support for inter-document xrefs as well.

**Comment by DavidGamba** [comment]
Not a problem, I am glad you were able to fix it properly.

**Comment by mojavelinux** [comment]
Let's hope so. I'll keep working to get #111 resolved as well.

**Pull request closed without merging**
