### PR TITLE
resolves #1093 allow column rule to be specified for columns in running content

### LINKED ISSUE #1093: Allowing borders on each of the columns in the running content
Allowing borders on each of the columns in the running content.

It's the follow up of  #1075 into a separate issue as asked by @mojavelinux .

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
@marcdexet-cnrs If you'd like to see this make it into beta.1, see if you're able to achieve the layout you want so I can determine if this is the right change.

**Comment by marcdexet-cnrs** [comment]
> 
> 
> @marcdexet-cnrs If you'd like to see this make it into beta.1, see if you're able to achieve the layout you want so I can determine if this is the right change.

Sure. Which branch should I use ?

**Comment by mojavelinux** [comment]
https://github.com/mojavelinux/asciidoctor-pdf/tree/issue-1093-running-content-column-rule

**Comment by marcdexet-cnrs** [comment]
I get a problem

```
base:
  font_size: 10
  font_size_large: $base_font_size * 1.25
  font_size_small: $base_font_size * 0.85

page:
  size: A4
  margin: [3.2cm, 1cm, 1cm, 1cm]

header:
  columns: <25% =50% >25%
  border_color: #dddddd
  border_style: solid
  column_rule_color: '333333'
  column_rule_width: 0.5
  recto:
    left:
      content: 'A name'
    center:
      content: '{doctitle}'
    right:
      content: |
        ref-doc: *{ref-doc}* +
        version: *{revnumber}* +
        date: {localdate} +
        page: *{page-number}/{page-count}*
  verso:
    left:
      content: $header_recto_left_content
    center:
      content: $header_recto_center_content      
    right:
      content: $header_recto_right_content
  height: 3cm
```

image

I try to adjust my properties, maybe there's something with my former values wrong.

**Comment by mojavelinux** [comment]
Nope, it's not your settings. The code is moving the cursor location and
not restoring it. That's the testing I was looking for.

Btw, you can use column_rule_spacing to move the text away from the line.

**Comment by mojavelinux** [comment]
It should be resolved now. Give it another shot.

**Comment by marcdexet-cnrs** [comment]
> 
> 
> It should be resolved now. Give it another shot.

I have no more header at all :)

image


Do you want my documentation and my theme file ?

**Comment by mojavelinux** [comment]
Your example works perfectly for me. Are you sure you updated the branch correctly? Try deleting it and pulling it down again.

**Comment by marcdexet-cnrs** [comment]
I check

**Comment by marcdexet-cnrs** [comment]
Yes ! It's good :)


I have removed but forgotten to checkout the right branch.

image

It's very good !!

**Pull request merged**
