### PR TITLE
resolves #191 allow theme to set paragraph indent (PR #192)

### LINKED ISSUE #191: Allow text-indent to be specified for paragraphs
Long prose works tend to use leading indentation for paragraphs to visually separate them instead of a paragraph gap. Allow the text-indent property to be set on the prose key (or perhaps the paragraph key) in the theme.

The key part of implementing this feature is getting paragraph indentation to work so that it respects the line spacing (a known issue in Prawn).

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
We still need to sort out where indentation is going to be applied and nail down which theme key to use.

**Comment by jstasiak** [comment]
Hey, a new asciidoctor user here. Thank you for this project. I'm preparing an ebook right and my first attempt at it involved using a word processor - it was a nightmare. asciidoctor seemed like a popular non-wysiwyg solution and so far I'm really happy with it. Granted, there are some rough edges in my case but I managed to work around some of them using custom styling and I intend to work around the rest by writing an extension.

One thing I need is paragraph indentation so I went ahead and rebased this branch on top of master and resolved the conflicts - everything seems to be working so far! Find the updated patch here: https://github.com/jstasiak/asciidoctor-pdf/commit/80c5ce01c5d3819dbf1e042114d35a5c6ca0dedd

Thank you once again!

**Comment by jstasiak** [comment]
Ok, it turns out it doesn't fully work. Let's have a document [x.txt](https://github.com/asciidoctor/asciidoctor-pdf/files/2402341/x.txt) with custom theme 
[custom-theme.yml.txt](https://github.com/asciidoctor/asciidoctor-pdf/files/2402342/custom-theme.yml.txt) (txt extension because GitHub demands it). I build a PDF like this:

```
bundle exec asciidoctor-pdf -a pdf-style=custom-theme.yml x.adoc
```

The relevant part of the document:

```
– xxxxxxxx, xx xx xxx xxxxxx xxxxxx xxxxxx – xxxxxx xxxxxxxx, xxxxxxxxxxxx xxx xxxxxxxxxxxx, xxxxxxxxxxxxx xxxxx. – xxxxxxxxx xx xxxxx xxxxxxx xxxxxxxxxx xxx x xxx, xx xxx xx xxxxxx xxxxxx. xxxxxxxxx xxxxxxxxx xxxxxxx xxxxxxxxx xxxxxxxx x xxxxx xxxxxxxxxxx x… – aaaaaaaaaaaa bb cccccc ddddddddddd:

11 11111111 1 1111111111

22222222222 22222,

33333, 3333333333 33333333,

44444 444444444444.

abcdefghijklmnop zzzzzzzzzzzzzzzzzz qqqqqqqqqqqqqq qqqaaaaaaaaaaaaaaaaaaaaax xx xx xxxxxxxx xxx, xxxxxxxxxxxx, xxxxx x xxxxxxxx x xxx xxxxxx xxxxxx. xxxxx… xxxxxxx xxxxx x xxxxxxx xxxxxxxxxx xxxx.
```

With https://github.com/jstasiak/asciidoctor-pdf/commit/80c5ce01c5d3819dbf1e042114d35a5c6ca0dedd I get this:

bad pdf

See how 2s, 3s, 4s and the part of the last paragraph before qs are missing. Now, since Prawn seems to support indenting paragraphs natively (a quick grep revealed this) I removed the custom formatting from the patch and let Prawn do its job (https://github.com/jstasiak/asciidoctor-pdf/commit/c61e1278dfd74bec58bd57bd68e593f9254be2fe) - maybe there's some edge case I haven't discovered yet but it looks good with my input:

good pdf

Note that it took me a while to find an issue with your patch as it heavily depends on the document. I tried to figure out why the custom rendering code doesn't work but I don't know Ruby well enough, I hope this is of some help.

**Comment by mojavelinux** [comment]
Yes, I can see where the flaw is. There's no need to set the :first_line_options option when using indent_paragraphs. That should only be used for the abstract.

**Pull request merged**
