### PR TITLE
partially address #6: support AsciiDoc table cell content

### PR DESCRIPTION
**Pull request by mojavelinux**
- support a limited subset of AsciiDoc table cell content (single block only)
- support a single image, paragraph, literal, listing, verse or quote in table cell
- show raw source for AsciiDoc table cell of other types
- add support for a literal table cell
- add support for a verse table cell

### CODE REVIEW

**Comment by mojavelinux** [comment]
I may have an idea for how to support more than one block in the AsciiDoc content. We can use a nested table with a single column and no borders. It's the no borders part I have to check. If this is possible, I'll update the pull request so that we can support any amount of AsciiDoc content. Of course, we still don't handle all types, like lists, but at least we wouldn't be dropping content.

**Comment by zachaller** [comment]
Whats the status of this, we are running into this and wondering when/if this plans on getting upstream.

**Comment by mojavelinux** [comment]
The plan is to get this into the next release, at least a first pass at it
as I mention. I need to first cleanup some of the code.

**Comment by antoyo** [comment]
Is this usable right now?
I tried to create a table with a list, a quote or a code block, but none of these works.
Here is the code I tried:

```asciidoc
[cols="1,1a", options="header"]
|===
| List
| Quote

|
* One
* Two
* Three

|
[quote, Albert Einstein]
A person who never made a mistake never tried anything new.
|===
```

And the result:

List | Quote
-----|---------
* One * Two * Tree | A person who never made a mistake never tried anything new.

I used the script `bin/asciidoctor-pdf` from the `issue-6` branch.

Thanks for your help.

**Comment by mojavelinux** [comment]
This is still very much in prototype, but I have a much better idea now of how to do it right. It's one of the first things I'm going to start working on when I get back to hacking on Asciidoctor PDF (likely December).

**Comment by antoyo** [comment]
My issue was caused by this line:

```asciidoc
[cols="1,1a", options="header"]
```

It should have been:

```asciidoc
[cols="1a,1a", options="header"]
```

By the way, I hacked the converter to be able to support code listing in table cells.

Here is the result:

screenshot

It would be nice to have a similar result when this feature is added.

**Comment by whatSocks** [comment]
+1

**Comment by mojavelinux** [comment]
Since this implementation is really a hack. I'm going to close it, but I'm happy to report I have a proper implementation coming.

**Comment by buffe** [comment]
hi @antoyo 

I tried with [cols="1a,3a"]  but it didn't format my list in the cell. is there anything special need to be done. 

Also  "a|" didn't work

**Comment by antoyo** [comment]
@buffe I used a branch that does not exist anymore and my current asciidoctor installation does not work anymore (bad luck :p ), so I cannot help you because I don't remember exactly what I did.
Maybe ask @mojavelinux if this branch (`issue-6`) was merged or not.

**Comment by buffe** [comment]
Ahh, Thanks @antoyo.  I will check on the issue-6.

**Pull request closed without merging**
